### ISSUE TITLE
0.1.1 seems to be broken (using windows)

### ISSUE THREAD

**Issue by oggs91** [Devisualization/window#10]
getting lots and lots of linker errors for 0.1.1, still works with 0.1.0
seems like a windows lib is missing

Compiling using dmd...
Linking...
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol SetWindowPo
s referenced in function _D15devisualization6window6window6Window4sizeMFNdkkZv
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol ShowWindow
referenced in function _D15devisualization6window6window6Window4showMFZv
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol BeginPaint
referenced in function _D15devisualization6window7context8buffer2d15Buffer2DCont
ext11swapBuffersMFNdZv
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol GetDC refer
enced in function _D15devisualization6window7context6opengl13OpenglContext6__cto
rMFC15devisualization6window6window6WindowS15devisualization6window10interfaces6
window12WindowConfigZC15devisualization6window7context6opengl13OpenglContext
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol CreateIconI
ndirect referenced in function _D15devisualization6window6window6Window4iconMFC1
5devisualization5image5image5ImageZv
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol GetClientRe
ct referenced in function _D15devisualization6window7context8buffer2d15Buffer2DC
ontext11swapBuffersMFNdZv
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol DefWindowPr
ocW referenced in function windowHandler
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol DispatchMes
sageW referenced in function _D15devisualization6window6window6Window20messageLo
opIterationFZb
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol CreateWindo
wExW referenced in function _D15devisualization6window6window12createWindowFiikk
PWPS7windows6HWND__kPkPmZPmPC15devisualization6window6window6WindowZPS7windows6H
WND__
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol CloseWindow
 referenced in function _D15devisualization6window6window6Window5closeMFNdZv
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol RegisterCla
ssW referenced in function _D15devisualization6window6window12createWindowFiikkP
WPS7windows6HWND__kPkPmZPmPC15devisualization6window6window6WindowZPS7windows6HW
ND__
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol SetWindowLo
ngW referenced in function _D15devisualization6window6window6Window4sizeMFNdkkZv

dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol LoadCursorW
 referenced in function _D15devisualization6window6window12createWindowFiikkPWPS
7windows6HWND__kPkPmZPmPC15devisualization6window6window6WindowZPS7windows6HWND_
_
dopenvg_demo_dwindow.obj : error LNK2019: unresolved external symbol AdjustWindo
wRectEx referenced in function _D15devisualization6window6window6Window4sizeMFNd

**Comment by rikkimax** [comment]
Unfortunately at some point I removed the libs to link with and never retested on 64bit only 32bit. It seems for 32bit dmd auto links to user32. But on 64bit it doesn't.

**Comment by rikkimax** [comment]
Ooo Github now auto closes if a commit references an issue. Reopen if it doesn't work. Tagged v0.1.2

**Comment by oggs91** [comment]
nvm, works again with 0.1.2, thx

**Comment by rikkimax** [comment]
No problem, was my fault.
